- name: install nginx
  hosts: WEB
  become: true
  tasks:
    - name: install nginx
      ansible.builtin.systemd:
        name: nginx
        state: latest


    - name: start nginx
      ansible.builtin.systemd:
        name: cron
        state: started
        enable: yes